spring:
  datasource:
    url: jdbc:h2:mem:taskdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

server:
  port: 8081

app:
  jwt:
    secret: "springangtaskssecretkeyforjwttoken256bitstrong"
    expirationMillis: 86400000 # 1 day

logging:
  level:
    root: INFO
    dev.zfir.springangtasks: INFO
